name: web
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  js: ^0.6.0
  cosy_webview_annotation:
    path: ./../../../dart/cosy_webview_annotation

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
